### ISSUE TITLE
Bug in TOC for appendix

### ISSUE THREAD

**Issue by katshun0307** [ksuenaga/kuisthesis-template#2]
There is a bug in displaying TOC for appendix.

* There is no page number
* There are no dots (･･････) that should appear between page number

---

* L. 453 of kuisthesis.sty seems to be related.
  * `\def\contentsline##1##2##3{\toc@contentsline{##1}{##2}{}}`
  * By commenting out L453, page number appears (but no dots appear between page number)
* There is a conflict with package hyperref. (But does not resolve this completely by removing)

---

## Temporary Workaround
A correct output can be obtained (without removing L.453) by...
1. Compile normally
2. Remove the line `\startappendixtoc` from `.toc` file 
3. Compile once again by `platex paper && dvipdfmx paper`

**Comment by katshun0307** [comment]
This bug was solved by using `\Appendix` instead of `\appendix`.

**Comment by ksuenaga** [comment]
@katshun0307 Does this style file define both `\Appendix` and `\appendix`?  Is this issue solved by redefining \appendix to be equal to \Appendix?

**Comment by katshun0307** [comment]
It seems to define both `\Appendix` and `\appendix`. 

I confirmed that the appendix shows up correctly even with `\appendix`, 
if I add the line: `\renewcommand{\appendix}{\Appendix}`  to the `.sty` file.

**Comment by ksuenaga** [comment]
@katshun0307 Done!  Thanks for reporting.

**Comment by aigarashi** [comment]
The difference between `\Appendix` and `\appendix` had been clearly documented but the commit d0ffa93 removed the description for some reason.  When this issue was opened, there was a discrepancy between the class file and its documentation.  This fix resulted in another discrepancy between the class file for a senior thesis, which we don't really take care of.   I find this situation rather confusing, though...
